version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'fix:'
    open-pull-requests-limit: 10
    target-branch: 'master'
    versioning-strategy: 'lockfile-only'
    rebase-strategy: 'auto'
