version: 2
registries:
  github-packages:
    type: 'npm-registry'
    url: 'https://npm.pkg.github.com'
    token: '${{ secrets.GH_PAT }}'

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'fix:'
    open-pull-requests-limit: 10
    target-branch: 'master'
    versioning-strategy: 'lockfile-only'
    rebase-strategy: 'auto'
    registries:
      - github-packages
