name: Install and Build
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Install Dependencies
        uses: ./.github/workflows/checkout-install.yml
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hosonokotaro'

      - name: Build
        run: npm run build
