name: Install and Build
on:
  pull_request:

jobs:
  checkout:
    uses: ./.github/workflows/checkout.yml
    with:
      node-version: '18'
      registry-url: 'https://npm.pkg.github.com'
      scope: '@hosonokotaro'

  build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build
