name: Push Tags
on:
  push:
    tags:
      - '*'
jobs:
  checkout:
    uses: ./.github/workflows/checkout.yml
    with:
      node-version: '18'
      registry-url: 'https://npm.pkg.github.com'
      scope: '@hosonokotaro'

  chromatic-deployment:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
