name: Release Package

on:
  release:
    types: [created]

jobs:
  checkout:
    uses: ./.github/workflows/checkout-install.yml
    with:
      node-version: '18'
      registry-url: 'https://npm.pkg.github.com'
      scope: '@hosonokotaro'

  publish-gpr:
    needs: checkout
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
